# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# CPU and RAM can be adjusted depending on your system
CPUCOUNT = "2"
RAM = "2048"


Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |
 config.vm.provider "libvirt"
 config.vm.synced_folder '.', '/vagrant', type: "rsync",
   owner: "vagrant", group: "vagrant"
 config.vm.provision :shell, path: "vagrant.sh"
 config.vm.network "private_network", type: "dhcp"

 config.vm.define "vvhost" do | vvhost |
   vvhost.vm.box = "generic/fedora29"
   vvhost.vm.hostname = "vvhost"
   

   vvhost.vm.provider "libvirt" do | libvirt |
     libvirt.memory = "2048"
     libvirt.cpus = 2
     libvirt.driver = "qemu"
   end
 end
end
