---

- name: Repmgr | Install repmgr
  apt:
    deb: "{{ item }}"
    update_cache: yes
  with_items:
    - "http://mothership.bazalt.team/vdi_stuff/deb/repmgr-common_5.2.1-1.stretch%2B1_all.deb"
    - "http://mothership.bazalt.team/vdi_stuff/deb/postgresql-9.6-repmgr_5.2.1-1.smolensk_amd64.deb"
