---

- name: Repmgr | install repmgr config
  template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_config }}"
    mode: 0644

- name: Repmgr | install sudo
  apt:
    name: sudo
    state: present

- name: Repmgr | add pg sudoers
  copy:
    src: pg_sudoers
    dest: "{{ sudoersd_dir }}/pg_sudoers"

- name: Repmgr | update pg hba
  blockinfile:
    dest: "{{ pg_hba_file }}"
    block: "{{ lookup('template', 'pg_hba.conf.j2') }}"
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR REPMGR"

- name: Repmgr | install pg config
  template:
    src: pg_repmgr.conf.j2
    dest: "{{ pg_confd_dir }}/pg_repmgr.conf"
    mode: 0644
    owner: postgres

- name: Repmgr | restart postgresql
  service:
    name: postgresql
    state: restarted

- name: Repmgr | add repmgr pgpass
  template:
    src: pgpass.j2
    dest: "~/.pgpass"
    mode: 0600
    owner: postgres
  become: true
  become_user: postgres
