---

- name: Postgres | Ensure pg_confd_dir
  file:
    path: "{{ pg_confd_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0775

- name: Postgres | Configure postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_conf_file }}"
    owner: postgres
    group: postgres
    mode: 0644
  notify:
    - restart postgresql

- name: Smolensk | Increase integrity level for user postgres
  command: pdpl-user -i 63 postgres
  when: ansible_os_family == "Astra Linux (Smolensk)"