---

- name: Make sure handlers are flushed immediately
  meta: flush_handlers

- block:
    - name: Build a sysctl_conf dynamic variable
      set_fact:
        sysctl_conf_dynamic_var: "{{ sysctl_conf_dynamic_var |default([]) }} + {{ sysctl_conf[item] | flatten(1) }}"  # yamllint disable rule:line-length
      loop: "{{ hostvars[inventory_hostname].group_names }}"

    - name: Setting kernel parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
      loop: "{{ sysctl_conf_dynamic_var|list | unique }}"
      when: sysctl_conf_dynamic_var | length > 0
  ignore_errors: true
  when: sysctl_set|bool
  tags: sysctl, kernel

...
