#

version: '3.7'
services:
  vdi-postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vdi
  vdi-redis:
    image: redis:5-alpine
    command: redis-server --requirepass 4NZ7GpHn4IlshPhb --bind 0.0.0.0
    depends_on:
      - vdi-postgres
  vdi-migrations:
    image: nexus.bazalt.team/veil-broker-backend:latest
    deploy:
      restart_policy:
        condition: none
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
      - VDI_BROKER_DB_HOST=vdi-postgres
    command: sh -c "sleep 5 && cd common/migrations && alembic upgrade head && exit 0"
    depends_on:
      - vdi-postgres
  vdi-tornado:
    image: nexus.bazalt.team/veil-broker-backend:latest
    deploy:
      replicas: 3
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
      - VDI_BROKER_DB_HOST=vdi-postgres
      - VDI_BROKER_REDIS_HOST=vdi-redis
    command: sh -c "python web_app/app.py --logging=DEBUG --address=0.0.0.0"
    depends_on:
      - vdi-postgres
      - vdi-redis
      - vdi-migrations
    expose:
      - "8888"
  vdi-pool-worker:
    image: nexus.bazalt.team/veil-broker-backend:latest
    deploy:
      replicas: 3
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
      - VDI_BROKER_DB_HOST=vdi-postgres
      - VDI_BROKER_REDIS_HOST=vdi-redis
    command: sh -c "python pool_worker/app.py"
    depends_on:
      - vdi-tornado
  vdi-monitor-worker:
    image: nexus.bazalt.team/veil-broker-backend:latest
    deploy:
      replicas: 3
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
      - VDI_BROKER_DB_HOST=vdi-postgres
      - VDI_BROKER_REDIS_HOST=vdi-redis
    command: sh -c "python monitor_worker/app.py"
    depends_on:
      - vdi-tornado
      - vdi-pool-worker
  vdi-angular:
    image: nexus.bazalt.team/veil-broker-frontend:latest
    deploy:
      replicas: 3
    command: sh -c "npm start --prefix /home/node/app/ -- --host=0.0.0.0 --disableHostCheck & npm run thin-client --prefix /home/node/app/ -- --host=0.0.0.0 --disableHostCheck"
    depends_on:
      - vdi-tornado
    expose:
      - "4200"
  vdi-guacamole:
    image: guacamole/guacd:1.3.0
    depends_on:
      - vdi-tornado
    expose:
      - "4822"
  vdi-nginx:
    image: nexus.bazalt.team/veil-broker-nginx:latest
    depends_on:
      - vdi-angular
    ports:
      - "443:443"
      - "80:80"
