FROM node:16-alpine
USER node
ADD --chown=node:node frontend /home/node/app
WORKDIR /home/node/app
RUN sed -i "s:127.0.0.1:vdi-tornado:g" "src/proxy.conf.json" && npm ci
ENV PATH=$PATH:/home/node/app/node_modules/.bin