name: base
channels:
  - conda-forge
dependencies:
  - python=3.7
  - postgresql=11
  - starlette
  - sanic
  - uvicorn
  - tornado

  - pip:
    - graphene
    - asyncpg
    - aiofiles
    - itsdangerous
    - pyjwt
    - python-dateutil
    - cached-property

    - sanic-jwt

    - ./../classy_async
    - ./../mi-pkg
    - ./.