name: base
channels:
  - conda-forge
dependencies:
  - python=3.7
  - postgresql=11
  - httptools
  - sanic
  - uvicorn
  - tornado

  - pip:
    - starlette
    - graphene
    - asyncpg
    - aiofiles
    - itsdangerous
    - pyjwt
    - python-dateutil
    - cached-property
    - docopt

    - sanic-jwt

    - -e ./classy_async
    - -e ./mi-pkg
    - -e ./.
    - -e ./auth_server