---

- name: Install Docker
  apt:
    name: docker.io
    update_cache: yes

- name: Add user to docker group
  user:
    name: "astravdi"
    groups: docker
    append: yes

- name: Load docker-images from tarball
  command: |
    docker load --input /media/cdrom/docker/{{ item }}.tar.gz
  with_items:
    - "postgres"
    - "redis"
    - "backend"
    - "frontend"
    - "guacamole"