#!/bin/bash

set -e
configure_secrets()
{
	# генерируем local_settings только если его не существует
	if [ ! -f /opt/veil-vdi/app/local_settings.py ]; then
		cd /opt/veil-vdi/app
		/opt/veil-vdi/env/bin/python /opt/veil-vdi/app/create_local_settings.py
	fi

	# берем из файла ключи доступа к БД и Redis
	DB_PASS="$(grep -r 'DB_PASS' /opt/veil-vdi/app/local_settings.py | sed -r "s/DB_PASS = '(.+)'/\1/g")"
	REDIS_PASS="$(grep -r 'REDIS_PASSWORD' /opt/veil-vdi/app/local_settings.py | sed -r "s/REDIS_PASSWORD = '(.+)'/\1/g")"

}
configure_redis()
{
	systemctl enable redis-server.service

	cp /opt/veil-vdi/other/vdi.redis /etc/redis/redis.conf
	# устанавливаем пароль для подключения
	echo "requirepass ${REDIS_PASS}" | tee -a /etc/redis/redis.conf

	systemctl restart redis-server
}

configure_postgres()
{
	cp /opt/veil-vdi/other/vdi.postgresql /etc/postgresql/9.6/main/postgresql.conf

	sed -i 's/peer/trust/g' /etc/postgresql/9.6/main/pg_hba.conf
	sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '127.0.0.1'/g" /etc/postgresql/9.6/main/postgresql.conf
	echo 'host  vdi postgres  0.0.0.0/0  trust' | tee -a /etc/postgresql/9.6/main/pg_hba.conf

	#fix locale
    localedef -i en_US -f UTF-8 en_US.UTF-8
	
	systemctl restart postgresql

	echo 'postgres:postgres' | sudo chpasswd
	sudo -u postgres -i psql -c "ALTER ROLE postgres PASSWORD '${DB_PASS}';"

	# на астре нету бездуховной кодировки en_US.UTF-8. Есть C.UTF-8
	sudo -u postgres -i psql -c "create database vdi encoding 'utf8' lc_collate = 'en_US.UTF-8' lc_ctype = 'en_US.UTF-8' template template0;" || true

	# apply database migrations

	export PYTHONPATH=/opt/veil-vdi/app
	cd /opt/veil-vdi/app
	/opt/veil-vdi/env/bin/python /opt/veil-vdi/env/bin/alembic upgrade head
}

configure_nginx()
{
	cp /opt/veil-vdi/other/vdi.nginx /etc/nginx/conf.d/vdi_nginx.conf
	rm /etc/nginx/sites-enabled/* || true
	systemctl restart nginx
}

configure_logs()
{
	# creating logs directory at /var/log/veil-vdi/
	mkdir -p /var/log/veil-vdi/ || true

	# deploying configuration files for logrotate
	cp /opt/veil-vdi/other/tornado.logrotate /etc/logrotate.d/veil-vdi
}

configure_supervisor()
{
	# deploying configuration files for supervisor
	rm /etc/supervisor/supervisord.conf || true
	cp /opt/veil-vdi/other/supervisord.conf /etc/supervisor/supervisord.conf

	supervisorctl reload
}

case "$1" in
	configure)
		# действия и при установке и при обновлении

		#configure_supervisor

		# действия только при установке
		if [ ! -n "$2" ] ; then
			configure_secrets
			configure_redis
			configure_postgres
			configure_nginx
			configure_logs
			configure_supervisor
		fi

		exit 0
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
		;;
	*)
		echo "postinst called with unknown argument: $*" >&2
		exit 1
		;;
esac
