name: base
channels:
  - conda-forge
dependencies:
  - python=3.7
  - postgresql=11
  - sanic
  - tornado
  - httptools

  - pip:
      - starlette
      - uvicorn
      - itsdangerous
      - graphene
      - asyncpg
      - pyjwt
      - python-dateutil
      - cached-property
      - docopt
      - websockets

      - sanic-jwt

# for fast edit use "-e"
# for prod "-e" not need
      - -e ./classy_async
      - -e ./mi-pkg
      - -e ./.
      - -e ./auth_server
