# если появляется новый пакет в зависимостях его нужно добавить в requirements.txt, затем выполнить
# docker system prune -a -f --volumes && docker-compose up
#
# guacamole port: 4822

version: '3.7'
services:
  vdi-postgres:
    image: postgres:11
    container_name: vdi-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    network_mode: "host"
  vdi-redis:
    image: redis:5
    container_name: vdi-redis
    command: redis-server --requirepass 4NZ7GpHn4IlshPhb --bind 0.0.0.0
    network_mode: "host"
    depends_on:
      - vdi-postgres
  vdi-tornado:
    build:
      context: ../../
      dockerfile: ./devops/docker/python/Dockerfile
    container_name: vdi-tornado
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
    working_dir: /opt/veil-vdi/app
    volumes:
      - ../../backend:/opt/veil-vdi/app
    command: sh -c "sleep 5 && pip install -U veil_api_client veil_aio_au && cd common/migrations && alembic upgrade head && cd ../../ && python web_app/app.py --logging=DEBUG"
    network_mode: "host"
    extra_hosts:
      - "ipa.bazalt.auth:192.168.14.83"
    depends_on:
      - vdi-postgres
      - vdi-redis
  vdi-pool-worker:
    build:
      context: ../../
      dockerfile: ./devops/docker/python/Dockerfile
    container_name: vdi-pool-worker
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
    working_dir: /opt/veil-vdi/app
    volumes:
      - ../../backend:/opt/veil-vdi/app
    command: sh -c "sleep 10 && pip install -U veil_api_client veil_aio_au && python pool_worker/app.py"
    network_mode: "host"
    depends_on:
      - vdi-tornado
  vdi-monitor-worker:
    build:
      context: ../../
      dockerfile: ./devops/docker/python/Dockerfile
    container_name: vdi-monitor-worker
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
    working_dir: /opt/veil-vdi/app
    volumes:
      - ../../backend:/opt/veil-vdi/app
    command: sh -c "sleep 15 && pip install -U veil_api_client veil_aio_au && python monitor_worker/app.py"
    network_mode: "host"
    depends_on:
      - vdi-tornado
      - vdi-pool-worker
  vdi-vm-manager:
    build:
      context: ../../
      dockerfile: ./devops/docker/python/Dockerfile
    container_name: vdi-vm-manager
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
    working_dir: /opt/veil-vdi/app
    volumes:
      - ../../backend:/opt/veil-vdi/app
    command: sh -c "sleep 15 && pip install -U veil_api_client veil_aio_au && python vm_manager/app.py"
    network_mode: "host"
    depends_on:
      - vdi-tornado
  vdi-angular:
    build:
      context: ../../
      dockerfile: ./devops/docker/angular/Dockerfile
    user: "node"
    container_name: vdi-angular
    working_dir: /home/node/app
    volumes:
      - ../../frontend:/home/node/app/frontend
    command: sh -c "npm start --prefix /home/node/app/frontend/ -- --host=0.0.0.0 --disableHostCheck & npm run thin-client --prefix /home/node/app/frontend/ -- --host=0.0.0.0 --disableHostCheck"
    network_mode: "host"
    depends_on:
      - vdi-tornado
  vdi-guacamole:
    image: guacamole/guacd:1.3.0
    container_name: vdi-guacamole
    network_mode: "host"
    depends_on:
      - vdi-tornado
