version: '3.7'

services:
  postgres:
    image: postgres:9.6
    ports:
        - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: vdi-postgres-alembic
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/