version: '3.7'
services:

  postgres:
    image: postgres:9.6
    ports:
        - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: vdi-postgres-alembic
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
#    TODO: alembic upgrade head

  redis:
    image: redis
    container_name: vdi-redis
    ports:
      - 6379:6379
    command: redis-server --requirepass 4NZ7GpHn4IlshPhb
