# docker-compose -f test-docker-compose.yml up --build --force-recreate -V --abort-on-container-exit --exit-code-from vdi-test-tornado
version: '3.7'
services:
  vdi-test-postgres:
    image: postgres:11
    container_name: vdi-test-postgres
    network_mode: "host"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
  vdi-test-redis:
    image: redis:5
    container_name: vdi-test-redis
    network_mode: "host"
    logging:
      driver: none
    command: redis-server --requirepass 4NZ7GpHn4IlshPhb --bind 0.0.0.0
  vdi-test-veil-server:
    build:
      context: ../../
      dockerfile: ./devops/docker/python/Dockerfile
    container_name: vdi-test-veil-server
    network_mode: "host"
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
    working_dir: /opt/veil-vdi/app
    volumes:
      - ../../backend/web_app/tests/veil_server:/opt/veil-vdi/app
    command: sh -c "echo 'running veil-test-server...' && python test_server.py"

  vdi-test-tornado:
    build:
      context: ../../
      dockerfile: ./devops/docker/python/Dockerfile
    container_name: vdi-test-tornado
    network_mode: "host"
    extra_hosts:
      - "ipa.bazalt.auth:192.168.14.83"
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - ASYNC_TEST_TIMEOUT=20
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
    working_dir: /opt/veil-vdi/app
    volumes:
      - ../../backend:/opt/veil-vdi/app
#    command: sh -c "sleep 10 && pip install -U veil_api_client veil_aio_au && cd /opt/veil-vdi/app/common/migrations && alembic upgrade head && cd /opt/veil-vdi/app/web_app/tests && pytest -m 'smoke_test' && pytest --cov=web_app --cov-report=html -vv -m 'not broken_runner'"
    command: /usr/sbin/tests_entry_point.sh
    depends_on:
      - vdi-test-postgres
      - vdi-test-redis
      - vdi-test-veil-server
      - vdi-test-pool-worker
  vdi-test-pool-worker:
    build:
      context: ../../
      dockerfile: ./devops/docker/python/Dockerfile
    container_name: vdi-test-pool-worker
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
    working_dir: /opt/veil-vdi/app
    volumes:
      - ../../backend:/opt/veil-vdi/app
    command: sh -c "sleep 10 && pip install -U veil_api_client veil_aio_au && python pool_worker/app.py"
    network_mode: "host"
    depends_on:
      - vdi-test-postgres
      - vdi-test-redis
      - vdi-test-veil-server
  vdi-test-vm-manager:
    build:
      context: ../../
      dockerfile: ./devops/docker/python/Dockerfile
    container_name: vdi-test-vm-manager
    environment:
      - PYTHONPATH=/opt/veil-vdi/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPYCACHEPREFIX=/tmp
    working_dir: /opt/veil-vdi/app
    volumes:
      - ../../backend:/opt/veil-vdi/app
    command: sh -c "sleep 10 && pip install -U veil_api_client veil_aio_au && python vm_manager/app.py"
    network_mode: "host"
    depends_on:
      - vdi-test-tornado

# manual run only
#  vdi-black:
#    image: mercutiodesign/docker-black
#    container_name: vdi-black
#    network_mode: "host"
#    environment:
#      - PYTHONPATH=/opt/veil-vdi/app
#    working_dir: /opt/veil-vdi/app
#    volumes:
#      - ../../backend:/opt/veil-vdi/app
#    command: sh -c "black ."
