"""pool table change structure v2

Revision ID: 139d96945c38
Revises: 319fb865f9a1
Create Date: 2019-11-08 20:03:10.746923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '139d96945c38'
down_revision = '319fb865f9a1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE TYPE status AS ENUM ('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automated_pool',
    sa.Column('pool_uid', postgresql.UUID(), nullable=False),
    sa.Column('datapool_uid', postgresql.UUID(), nullable=False),
    sa.Column('template_uid', postgresql.UUID(), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('max_vm_amount', sa.Integer(), nullable=False),
    sa.Column('increase_step', sa.Integer(), nullable=False),
    sa.Column('max_amount_of_create_attempts', sa.Integer(), nullable=False),
    sa.Column('initial_size', sa.Integer(), nullable=False),
    sa.Column('reserve_size', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('vm_name_template', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pool_uid'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('pool_uid')
    )
    op.create_table('static_pool',
    sa.Column('pool_uid', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pool_uid'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('pool_uid')
    )
    op.add_column('pool', sa.Column('status', sa.Enum('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL', name='status'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'status')
    op.drop_table('static_pool')
    op.drop_table('automated_pool')
    # ### end Alembic commands ###
    op.execute("DROP TYPE status CASCADE;")
