"""pool table change structure v1

Revision ID: 319fb865f9a1
Revises: 747034e9b106
Create Date: 2019-11-08 17:21:03.835756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '319fb865f9a1'
down_revision = '747034e9b106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE pool CASCADE;')
    op.create_unique_constraint(None, 'controller', ['address'])
    op.add_column('pool', sa.Column('cluster_uid', postgresql.UUID(), nullable=False))
    op.add_column('pool', sa.Column('node_uid', postgresql.UUID(), nullable=False))
    op.alter_column('pool', 'controller',
                    existing_type=postgresql.UUID(),
                    nullable=False)
    op.drop_column('pool', 'datapool_id')
    op.drop_column('pool', 'vm_name_template')
    op.drop_column('pool', 'template_id')
    op.drop_column('pool', 'node_id')
    op.drop_column('pool', 'initial_size')
    op.drop_column('pool', 'dynamic_traits')
    op.drop_column('pool', 'total_size')
    op.drop_column('pool', 'desktop_pool_type')
    op.drop_column('pool', 'reserve_size')
    op.drop_column('pool', 'status')
    op.drop_column('pool', 'cluster_id')
    op.drop_column('pool', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('cluster_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('status', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('pool', sa.Column('reserve_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('desktop_pool_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('pool', sa.Column('total_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pool', sa.Column('dynamic_traits', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('initial_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('node_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('template_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('vm_name_template', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('datapool_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('pool', 'controller',
                    existing_type=postgresql.UUID(),
                    nullable=True)
    op.drop_column('pool', 'node_uid')
    op.drop_column('pool', 'cluster_uid')
    op.drop_constraint(None, 'controller', type_='unique')
    # ### end Alembic commands ###
