"""init

Revision ID: 64cb2fb49e3e
Revises: 
Create Date: 2019-10-07 19:41:10.563126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64cb2fb49e3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controllers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('verbose_name', sa.Unicode(length=128), nullable=False),
    sa.Column('status', sa.Unicode(length=128), nullable=True),
    sa.Column('address', sa.Unicode(length=15), nullable=False),
    sa.Column('description', sa.Unicode(length=256), nullable=True),
    sa.Column('version', sa.Unicode(length=128), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.Unicode(length=128), nullable=False),
    sa.Column('password', sa.Unicode(length=128), nullable=False),
    sa.Column('email', sa.Unicode(length=256), nullable=True),
    sa.Column('first_name', sa.Unicode(length=32), nullable=True),
    sa.Column('last_name', sa.Unicode(length=128), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pools',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('verbose_name', sa.Unicode(length=128), nullable=False),
    sa.Column('status', sa.Unicode(length=128), nullable=False),
    sa.Column('controller', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['controller'], ['controllers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pools')
    op.drop_table('users')
    op.drop_table('controllers')
    # ### end Alembic commands ###
