"""some cascade for foreign keys

Revision ID: 73db88634464
Revises: 118c42fdf02e
Create Date: 2019-11-26 19:14:26.873710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73db88634464'
down_revision = '118c42fdf02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('automated_pool_automated_pool_id_fkey', 'automated_pool', type_='foreignkey')
    op.create_foreign_key(None, 'automated_pool', 'pool', ['automated_pool_id'], ['pool_id'], ondelete='CASCADE')
    op.drop_constraint('pool_controller_fkey', 'pool', type_='foreignkey')
    op.create_foreign_key(None, 'pool', 'controller', ['controller'], ['id'], ondelete='CASCADE')
    op.drop_constraint('pools_users_pool_id_fkey', 'pools_users', type_='foreignkey')
    op.drop_constraint('pools_users_user_id_fkey', 'pools_users', type_='foreignkey')
    op.create_foreign_key(None, 'pools_users', 'pool', ['pool_id'], ['pool_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pools_users', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('static_pool_static_pool_id_fkey', 'static_pool', type_='foreignkey')
    op.create_foreign_key(None, 'static_pool', 'pool', ['static_pool_id'], ['pool_id'], ondelete='CASCADE')
    op.drop_constraint('vm_pool_id_fkey', 'vm', type_='foreignkey')
    op.create_foreign_key(None, 'vm', 'pool', ['pool_id'], ['pool_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vm', type_='foreignkey')
    op.create_foreign_key('vm_pool_id_fkey', 'vm', 'pool', ['pool_id'], ['pool_id'])
    op.drop_constraint(None, 'static_pool', type_='foreignkey')
    op.create_foreign_key('static_pool_static_pool_id_fkey', 'static_pool', 'pool', ['static_pool_id'], ['pool_id'])
    op.drop_constraint(None, 'pools_users', type_='foreignkey')
    op.drop_constraint(None, 'pools_users', type_='foreignkey')
    op.create_foreign_key('pools_users_user_id_fkey', 'pools_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key('pools_users_pool_id_fkey', 'pools_users', 'pool', ['pool_id'], ['pool_id'])
    op.drop_constraint(None, 'pool', type_='foreignkey')
    op.create_foreign_key('pool_controller_fkey', 'pool', 'controller', ['controller'], ['id'])
    op.drop_constraint(None, 'automated_pool', type_='foreignkey')
    op.create_foreign_key('automated_pool_automated_pool_id_fkey', 'automated_pool', 'pool', ['automated_pool_id'], ['pool_id'])
    # ### end Alembic commands ###
