"""pool table change structure v2

Revision ID: 80c04faf2107
Revises: 319fb865f9a1
Create Date: 2019-11-12 19:40:01.979167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80c04faf2107'
down_revision = '319fb865f9a1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        "CREATE TYPE status AS ENUM ('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL', 'BAD_AUTH');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automated_pool',
    sa.Column('automated_pool_id', postgresql.UUID(), nullable=False),
    sa.Column('datapool_id', postgresql.UUID(), nullable=False),
    sa.Column('template_id', postgresql.UUID(), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('max_vm_amount', sa.Integer(), nullable=False),
    sa.Column('increase_step', sa.Integer(), nullable=False),
    sa.Column('max_amount_of_create_attempts', sa.Integer(), nullable=False),
    sa.Column('initial_size', sa.Integer(), nullable=False),
    sa.Column('reserve_size', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('vm_name_template', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['automated_pool_id'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('automated_pool_id')
    )
    op.create_table('static_pool',
    sa.Column('static_pool_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['static_pool_id'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('static_pool_id')
    )
    op.add_column('pool', sa.Column('cluster_id', postgresql.UUID(), nullable=False))
    op.add_column('pool', sa.Column('node_id', postgresql.UUID(), nullable=False))
    op.add_column('pool', sa.Column('status', sa.Enum('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL', 'BAD_AUTH', name='status'), nullable=False))
    op.drop_column('pool', 'cluster_uid')
    op.drop_column('pool', 'node_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('node_uid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('pool', sa.Column('cluster_uid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('pool', 'status')
    op.drop_column('pool', 'node_id')
    op.drop_column('pool', 'cluster_id')
    op.drop_table('static_pool')
    op.drop_table('automated_pool')
    # ### end Alembic commands ###
    op.execute("DROP TYPE status CASCADE;")

