"""pool table change structure v3

Revision ID: 84a595a83c57
Revises: 80c04faf2107
Create Date: 2019-11-13 13:38:41.082034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a595a83c57'
down_revision = '80c04faf2107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pool_status'), 'pool', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pool_status'), table_name='pool')
    # ### end Alembic commands ###
