"""user token store

Revision ID: a3c6e48b642f
Revises: d0515c7e5aac
Create Date: 2019-11-21 20:33:56.397379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3c6e48b642f'
down_revision = 'd0515c7e5aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_jwtinfo',
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('token', sa.Unicode(), nullable=False),
    sa.Column('last_changed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_jwtinfo_token'), 'user_jwtinfo', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_jwtinfo_token'), table_name='user_jwtinfo')
    op.drop_table('user_jwtinfo')
    # ### end Alembic commands ###
