"""pool table change structure v2

Revision ID: af7ab387e939
Revises: 319fb865f9a1
Create Date: 2019-11-08 17:24:39.908156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af7ab387e939'
down_revision = '319fb865f9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE status AS ENUM ('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL');")
    op.create_table('automated_pool',
    sa.Column('pool_id', postgresql.UUID(), nullable=True),
    sa.Column('datapool_uid', postgresql.UUID(), nullable=False),
    sa.Column('template_uid', postgresql.UUID(), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('max_vm_amount', sa.Integer(), nullable=False),
    sa.Column('increase_step', sa.Integer(), nullable=False),
    sa.Column('max_amount_of_create_attempts', sa.Integer(), nullable=False),
    sa.Column('initial_size', sa.Integer(), nullable=False),
    sa.Column('reserve_size', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('vm_name_template', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], )
    )
    op.create_table('static_pool',
    sa.Column('pool_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], )
    )
    op.add_column('pool', sa.Column('status', sa.Enum('creating', 'active', 'failed', 'deleting', 'service', 'partial', name='status'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'status')
    op.drop_table('static_pool')
    op.drop_table('automated_pool')
    op.execute("DROP TYPE status;")
    # ### end Alembic commands ###
