"""vm_table_username_nullable

Revision ID: c61c8ef17e40
Revises: 80c04faf2107
Create Date: 2019-11-13 16:13:49.445888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61c8ef17e40'
down_revision = '747034e9b106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pool', ['verbose_name'])
    op.alter_column('vm', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vm', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'pool', type_='unique')
    # ### end Alembic commands ###
