"""Pool model updates2

Revision ID: ee551f6deb00
Revises: f8ed0913e9f4
Create Date: 2019-11-07 18:15:33.965399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee551f6deb00'
down_revision = 'f8ed0913e9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE desktop_pool_type AS ENUM ('AUTOMATED', 'STATIC');")
    op.add_column('pool', sa.Column('cluster_id', postgresql.UUID(), nullable=True))
    op.add_column('pool', sa.Column('datapool_id', postgresql.UUID(), nullable=True))
    op.add_column('pool', sa.Column('desktop_pool_type', sa.Enum('AUTOMATED', 'STATIC', name='desktop_pool_type'), nullable=False))
    op.add_column('pool', sa.Column('node_id', postgresql.UUID(), nullable=True))
    op.add_column('pool', sa.Column('template_id', postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'template_id')
    op.drop_column('pool', 'node_id')
    op.drop_column('pool', 'desktop_pool_type')
    op.drop_column('pool', 'datapool_id')
    op.drop_column('pool', 'cluster_id')
    op.execute("DROP TYPE desktop_pool_type;")
    # ### end Alembic commands ###
