"""add event

Revision ID: eeb6ef3b11c5
Revises: 27386d7871d2
Create Date: 2019-11-21 18:03:15.721022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eeb6ef3b11c5'
down_revision = '27386d7871d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('event_type', sa.Integer(), nullable=False),
    sa.Column('message', sa.Unicode(length=256), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'controller', ['verbose_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'controller', type_='unique')
    op.drop_table('event')
    # ### end Alembic commands ###
