"""initial

Revision ID: f6da15d7a43d
Revises: 
Create Date: 2019-10-31 16:01:37.233356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6da15d7a43d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controller',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('verbose_name', sa.Unicode(length=128), nullable=False),
    sa.Column('status', sa.Unicode(length=128), nullable=True),
    sa.Column('address', sa.Unicode(length=15), nullable=False),
    sa.Column('description', sa.Unicode(length=256), nullable=True),
    sa.Column('version', sa.Unicode(length=128), nullable=True),
    sa.Column('username', sa.Unicode(length=128), nullable=False),
    sa.Column('password', sa.Unicode(length=128), nullable=False),
    sa.Column('ldap_connection', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Unicode(length=1024), nullable=True),
    sa.Column('expires_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('username', sa.Unicode(length=128), nullable=False),
    sa.Column('password', sa.Unicode(length=128), nullable=False),
    sa.Column('email', sa.Unicode(length=256), nullable=True),
    sa.Column('first_name', sa.Unicode(length=32), nullable=True),
    sa.Column('last_name', sa.Unicode(length=128), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pool',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('verbose_name', sa.Unicode(length=128), nullable=False),
    sa.Column('status', sa.Unicode(length=128), nullable=False),
    sa.Column('controller', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('desktop_pool_type', sa.Unicode(length=255), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('dynamic_traits', sa.Integer(), nullable=True),
    sa.Column('datapool_id', sa.Unicode(length=100), nullable=True),
    sa.Column('cluster_id', sa.Unicode(length=100), nullable=True),
    sa.Column('node_id', sa.Unicode(length=100), nullable=True),
    sa.Column('template_id', sa.Unicode(length=100), nullable=True),
    sa.Column('initial_size', sa.Integer(), nullable=True),
    sa.Column('reserve_size', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('vm_name_template', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['controller'], ['controller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pools_users',
    sa.Column('pool_id', postgresql.UUID(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('vm',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('template_id', sa.Unicode(length=100), nullable=True),
    sa.Column('pool_id', postgresql.UUID(), nullable=True),
    sa.Column('username', sa.Unicode(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm')
    op.drop_table('pools_users')
    op.drop_table('pool')
    op.drop_table('user')
    op.drop_table('controller')
    # ### end Alembic commands ###
