"""change_table_pool_colunm_keep_vms_on

Revision ID: f7a3e4780221
Revises: 27386d7871d2
Create Date: 2019-11-21 17:52:30.475470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a3e4780221'
down_revision = '27386d7871d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('keep_vms_on', sa.Boolean(), nullable=False, server_default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'keep_vms_on')
    # ### end Alembic commands ###
