"""Pool model updates

Revision ID: f8ed0913e9f4
Revises: 747034e9b106
Create Date: 2019-11-07 18:15:13.222856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ed0913e9f4'
down_revision = '747034e9b106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'controller', ['address'])
    op.add_column('pool', sa.Column('increase_step', sa.Integer(), nullable=False))
    op.add_column('pool', sa.Column('max_amount_of_create_attempts', sa.Integer(), nullable=False))
    op.add_column('pool', sa.Column('max_size', sa.Integer(), nullable=False))
    op.add_column('pool', sa.Column('max_vm_amount', sa.Integer(), nullable=False))
    op.add_column('pool', sa.Column('min_size', sa.Integer(), nullable=False))
    op.drop_column('pool', 'desktop_pool_type')
    op.drop_column('pool', 'cluster_id')
    op.drop_column('pool', 'template_id')
    op.drop_column('pool', 'node_id')
    op.drop_column('pool', 'datapool_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('datapool_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('node_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('template_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('cluster_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('desktop_pool_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('pool', 'min_size')
    op.drop_column('pool', 'max_vm_amount')
    op.drop_column('pool', 'max_size')
    op.drop_column('pool', 'max_amount_of_create_attempts')
    op.drop_column('pool', 'increase_step')
    op.drop_constraint(None, 'controller', type_='unique')
    # ### end Alembic commands ###
