"""auth_dir model

Revision ID: fd8fe108d273
Revises: 73db88634464
Create Date: 2019-11-28 17:40:32.435800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd8fe108d273'
down_revision = '73db88634464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication_directory',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('verbose_name', sa.Unicode(length=255), nullable=True),
    sa.Column('connection_type', sa.Enum('LDAP', name='connectiontypes'), server_default='LDAP', nullable=False),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('directory_url', sa.Unicode(length=255), nullable=True),
    sa.Column('directory_type', sa.Enum('ActiveDirectory', name='directorytypes'), server_default='ActiveDirectory', nullable=False),
    sa.Column('domain_name', sa.Unicode(length=255), nullable=True),
    sa.Column('subdomain_name', sa.Unicode(length=255), nullable=True),
    sa.Column('service_username', sa.Unicode(length=150), nullable=True),
    sa.Column('service_password', sa.Unicode(length=128), nullable=True),
    sa.Column('admin_server', sa.Unicode(length=255), nullable=True),
    sa.Column('kdc_urls', postgresql.ARRAY(sa.Unicode(length=255)), nullable=True),
    sa.Column('sso', sa.Boolean(), nullable=True),
                    sa.Column('status',
                              postgresql.ENUM('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL',
                                              'BAD_AUTH', name='status', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name'),
    sa.UniqueConstraint('verbose_name')
    )
    op.create_index(op.f('ix_authentication_directory_status'), 'authentication_directory', ['status'], unique=False)
    op.drop_constraint('user_jwtinfo_user_id_fkey', 'user_jwtinfo', type_='foreignkey')
    op.create_foreign_key(None, 'user_jwtinfo', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'email', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_jwtinfo_user_id_fkey', 'user_jwtinfo', type_='foreignkey')
    op.create_foreign_key('user_jwtinfo_user_id_fkey', 'user_jwtinfo', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_authentication_directory_status'), table_name='authentication_directory')
    op.drop_table('authentication_directory')
    # ### end Alembic commands ###
