---

- name: Broker | Add repo key
  apt_key:
    url: "{{ broker_apt_key_url }}"
    state: present

- name: Broker | Add apt repo
  apt_repository:
    repo: "{{ broker_apt_repo }}"
    state: present

- name: Broker | Install broker packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: "{{ broker_packages_list }}"

- name: Broker | Stop broker services
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ broker_services_list }}"

- name: Broker | Register db password
  shell: grep -r 'DB_PASS' /opt/veil-vdi/app/common/local_settings.py | sed -r "s/DB_PASS = '(.+)'/\1/g"
  no_log: true
  register: broker_db_pass

- name: Broker | Convert db password to md5 hash
  shell: echo -n {{ broker_db_pass.stdout }}{{ broker_db_user }} | md5sum | cut -d" " -f1
  no_log: true
  register: broker_db_pass_md5

- name: Broker | Create db user
  postgresql_user:
    name: "{{ broker_db_user }}"
    password: "{{ broker_db_pass.stdout }}"
    role_attr_flags: LOGIN
  no_log: true
  become: true
  become_user: postgres
  delegate_to: "{{ item }}"
  with_items: "{{ groups.master[0] }}"

- name: Broker | Create database
  postgresql_db:
    name: "{{ broker_db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    owner: "{{ broker_db_user }}"
  become: true
  become_user: postgres
  delegate_to: "{{ item }}"
  with_items: "{{ groups.master[0] }}"

- name: Broker | Update pg_hba.conf
  blockinfile:
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    block: "{{ lookup('template', 'pg_hba.conf.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR BROKER"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['postgres_cluster'] }}"

- name: Broker | Update pgbouncer users
  lineinfile:
    dest: "{{ pgbouncer_conf_dir }}/userlist.txt"
    line: '"{{ broker_db_user }}" "md5{{ broker_db_pass_md5.stdout }}"'
  no_log: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['postgres_cluster'] }}"

- name: Broker | Reload services
  service:
    name: "{{ item.0 }}"
    state: reloaded
  delegate_to: "{{ item.1 }}"
  with_nested:
    - ['postgresql', 'pgbouncer']
    - "{{ groups['postgres_cluster'] }}"

- name: Broker | Configure db connection
  blockinfile:
    path: "{{ broker_local_settings }}"
    block: |
      DB_HOST = '{{ cluster_vip }}'
      DB_PORT = {{ pgbouncer_listen_port }}
      DB_NAME = '{{ broker_db_name }}'
      DB_USER = '{{ broker_db_user }}'

- name: Broker | Apply migrations
  command: "/opt/veil-vdi/env/bin/python /opt/veil-vdi/env/bin/alembic upgrade head"
  args:
    chdir: "/opt/veil-vdi/app/common/migrations"
  environment:
    PYTHONPATH: "/opt/veil-vdi/app"

- name: Broker | Start broker services
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ broker_services_list }}"