#!/bin/bash

set -e

configure_users()
{
	VDIADMIN="vdiadmin"
	VDIADMIN_PASS="Bazalt1!"

	groupadd -f vdi-web
	groupadd -f vdi-web-admin
	if ! id "$VDIADMIN" &>/dev/null; then
		useradd -G vdi-web,vdi-web-admin,shadow -s /sbin/nologin $VDIADMIN
		echo "$VDIADMIN:$VDIADMIN_PASS" | chpasswd
	fi
	chmod 755 /usr/sbin/vdi_sso_setting.sh
}

configure_secrets()
{
	# generate local_settings.py if not exists
	if [ ! -f /opt/veil-vdi/app/common/local_settings.py ]; then
		export PYTHONPATH=/opt/veil-vdi/app
		cd /opt/veil-vdi/app
		/opt/veil-vdi/env/bin/python /opt/veil-vdi/app/common/create_local_settings.py -f /opt/veil-vdi/app/common/local_settings.py
		chmod 600 /opt/veil-vdi/app/common/local_settings.py
	fi

	chmod 600 /opt/veil-vdi/app/common/settings.py
	chown -R $VDIADMIN:$VDIADMIN /opt/veil-vdi
}

configure_logs()
{
	# creating logs directory at /var/log/veil-vdi
	mkdir -p /var/log/veil-vdi
	chown -R $VDIADMIN:$VDIADMIN /var/log/veil-vdi

	touch /var/log/faillog
	chmod 666 /var/log/faillog

	# deploying configuration files for logrotate
	cp /opt/veil-vdi/other/tornado.logrotate /etc/logrotate.d/veil-vdi
}

configure_systemd()
{
	systemctl daemon-reload
	systemctl enable vdi-web vdi-pool_worker vdi-vm_manager vdi-monitor_worker
}

configure_crontab()
{
	# add archive_csv_journal.sh to crontab
	echo "$(echo '1 1 * * * /bin/bash /opt/veil-vdi/app/archive_csv_journal.sh' ; crontab -l)" | crontab -
}

db_migrations()
{
	systemctl stop vdi-web vdi-pool_worker vdi-vm_manager vdi-monitor_worker

	echo "Apply database migrations..."
	export PYTHONPATH=/opt/veil-vdi/app
	cd /opt/veil-vdi/app/common/migrations
	/opt/veil-vdi/env/bin/python /opt/veil-vdi/env/bin/alembic upgrade head

	systemctl start vdi-web vdi-pool_worker vdi-vm_manager vdi-monitor_worker
}

case "$1" in
	configure)
		# install and upgrade
		configure_systemd

		if [ -z "$2" ] ; then
			# install only
			configure_users
			configure_secrets
			configure_logs
			configure_crontab
		else
			# upgrade only
			db_migrations
		fi

		exit 0
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
		;;
	*)
		echo "postinst called with unknown argument: $*" >&2
		exit 1
		;;
esac