---

- name: Add repo key
  apt_key:
    data: "{{ lookup('file', 'veil-repo-key.gpg') }}"
    state: present

- name: Add apt repo
  apt_repository:
    repo: "{{ broker_apt_repo }}"
    state: present

- name: Install system packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ broker_system_packages_list }}"

- name: Install broker packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ broker_packages_list }}"

- name: Stop broker services
  service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ broker_services_list }}"

- name: Register db password
  shell: grep -r 'DB_PASS' /opt/veil-vdi/app/common/local_settings.py | sed -r "s/DB_PASS = '(.+)'/\1/g"
  no_log: true
  register: broker_db_pass

# postgresql role
- include_role:
    name: postgresql
  vars:
    postgresql_db_pass: "{{ broker_db_pass.stdout }}"

- name: Configure db connection
  blockinfile:
    path: "{{ broker_local_settings }}"
    block: |
      DB_NAME = '{{ broker_db_name }}'
      DB_USER = '{{ broker_db_user }}'
      LOCAL_AUTH = True
      PAM_AUTH = False

- name: Apply migrations
  command: "/opt/veil-vdi/env/bin/python /opt/veil-vdi/env/bin/alembic upgrade head"
  args:
    chdir: "/opt/veil-vdi/app/common/migrations"
  environment:
    PYTHONPATH: "/opt/veil-vdi/app"

# apache2 tasks
- import_tasks: apache2.yml

# redis-server tasks
- import_tasks: redis-server.yml

# awstats tasks
- import_tasks: awstats.yml

# guacamole tasks
- import_tasks: guacamole.yml

- name: Start broker services
  service:
    name: "{{ item }}"
    state: started
  loop: "{{ broker_services_list }}"

- name: Remove apt repo
  apt_repository:
    repo: "{{ broker_apt_repo }}"
    state: absent
  notify:
    - apt update