---

- name: Broker | Add repo key
  apt_key:
    data: "{{ lookup('file', 'veil-repo-key.gpg') }}"
    state: present

- name: Broker | Add apt repo
  apt_repository:
    repo: "{{ broker_apt_repo }}"
    state: present

- name: Broker | Install system packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ broker_system_packages_list }}"

- name: Broker | Install broker packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ broker_packages_list }}"

- name: Broker | Stop broker services
  service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ broker_services_list }}"

# postgresql tasks
- import_tasks: postgresql.yml

- name: Broker | Configure db connection
  blockinfile:
    path: "{{ broker_local_settings }}"
    block: |
      {% if with_pgcluster|bool %}
      DB_HOST = '{{ cluster_vip }}'
      DB_PORT = {{ pgbouncer_listen_port }}
      {% endif %}
      DB_NAME = '{{ broker_db_name }}'
      DB_USER = '{{ broker_db_user }}'
      LOCAL_AUTH = False
      PAM_AUTH = True

- name: Broker | Apply migrations
  command: "/opt/veil-vdi/env/bin/python /opt/veil-vdi/env/bin/alembic upgrade head"
  args:
    chdir: "/opt/veil-vdi/app/common/migrations"
  environment:
    PYTHONPATH: "/opt/veil-vdi/app"

# apache2 tasks
- import_tasks: apache2.yml

# redis-server tasks
- import_tasks: redis-server.yml

# awstats tasks
- import_tasks: awstats.yml

# guacamole tasks
- import_tasks: guacamole.yml

- name: Broker | Start broker services
  service:
    name: "{{ item }}"
    state: started
  loop: "{{ broker_services_list }}"

- name: Broker | Remove apt repo
  apt_repository:
    repo: "{{ broker_apt_repo }}"
    state: absent
  notify:
    - apt update