---

- name: Broker | Install postgresql
  apt:
    name: "postgresql-{{ broker_postgresql_version }}"
    update_cache: yes

- name: Broker | Configure postgresql
  template:
    src: postgresql.conf.j2
    dest: "{{ broker_postgresql_conf_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify:
    - restart postgresql

- name: Broker | Register db password
  shell: grep -r 'DB_PASS' /opt/veil-vdi/app/common/local_settings.py | sed -r "s/DB_PASS = '(.+)'/\1/g"
  no_log: true
  register: broker_db_pass

- name: Broker | Create db user
  postgresql_user:
    name: "{{ broker_db_user }}"
    password: "{{ broker_db_pass.stdout }}"
    role_attr_flags: LOGIN,SUPERUSER
  no_log: true
  become: true
  become_user: postgres

- name: Broker | Create database
  postgresql_db:
    name: "{{ broker_db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    owner: "{{ broker_db_user }}"
  become: true
  become_user: postgres

- name: Broker | Create db extension
  postgresql_ext:
    name: "{{ item }}"
    db: "{{ broker_db_name }}"
  become: true
  become_user: postgres
  loop: "{{ broker_pg_ext_list }}"