---

- name: Install redis-server
  apt:
    name: redis-server
    update_cache: yes

- name: Enable service redis-server
  service:
    name: redis-server
    enabled: yes

- name: Configure redis.conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: 0640

- name: Register redis password
  shell: grep -r 'REDIS_PASSWORD' /opt/veil-vdi/app/common/local_settings.py | sed -r "s/REDIS_PASSWORD = '(.+)'/\1/g"
  no_log: true
  register: broker_redis_pass

- name: Set redis password
  lineinfile:
    dest: /etc/redis/redis.conf
    line: 'requirepass {{ broker_redis_pass.stdout }}'
  no_log: true
  register: broker_redis_pass_set_result

- name: Restart service redis-server
  service:
    name: redis-server
    state: restarted
  when: broker_redis_pass_set_result.changed