"""Task   started finished colunms

Revision ID: 004d0c8a20aa
Revises: 69d6bd97f61e
Create Date: 2020-11-02 13:38:44.901199

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '004d0c8a20aa'
down_revision = '69d6bd97f61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('finished', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task', sa.Column('started', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'started')
    op.drop_column('task', 'finished')
    # ### end Alembic commands ###
