"""tk connections add mac and hostname

Revision ID: 17997eb1f91f
Revises: 9d14f7f75d65
Create Date: 2022-01-20 11:19:07.353426

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '17997eb1f91f'
down_revision = '9d14f7f75d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_tk_connection', sa.Column('hostname', sa.Unicode(length=128), nullable=True))
    op.add_column('active_tk_connection', sa.Column('mac_address', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_tk_connection', 'mac_address')
    op.drop_column('active_tk_connection', 'hostname')
    # ### end Alembic commands ###
