"""Vm status field

Revision ID: 1b23d22179d7
Revises: 8851d2ea916b
Create Date: 2020-10-16 11:19:37.510509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1b23d22179d7'
down_revision = '8851d2ea916b'
branch_labels = None
depends_on = None


def upgrade():
    # Пропущенный индекс в предыдущих миграциях
    op.create_index(op.f('ix_task_task_type'), 'task', ['task_type'], unique=False)
    # Добавляем статус для ВМ
    op.add_column('vm', sa.Column('status',
                                  sa.Enum('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL', 'BAD_AUTH',
                                          name='status'), nullable=True))
    # Применяем изменения для существующих записей
    op.execute("""update public.vm set status ='ACTIVE'""")
    op.alter_column('vm', 'status',
                    existing_type=postgresql.ENUM('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL',
                                                  'BAD_AUTH', name='status'),
                    nullable=False)
    op.create_index(op.f('ix_vm_status'), 'vm', ['status'], unique=False)
    # Убираем бесполезное поле
    op.drop_column('vm', 'broken')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('broken', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute("""update public.vm set broken = False""")
    op.alter_column('vm', 'assigned_to_user',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.drop_index(op.f('ix_vm_status'), table_name='vm')
    op.drop_column('vm', 'status')
    op.drop_index(op.f('ix_task_task_type'), table_name='task')
    # ### end Alembic commands ###
