"""add_reserved_status

Revision ID: 25b755d488b3
Revises: db24ab713002
Create Date: 2021-02-08 19:11:31.730156

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '25b755d488b3'
down_revision = 'db24ab713002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update vm set status = 'BAD_AUTH' where status = 'SERVICE'")
    # rename the old enum
    op.execute("alter type status rename to old_status;")
    # create the new enum
    op.execute("create type status as enum ('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL', 'BAD_AUTH', 'RESERVED');")

    # alter all you enum columns
    op.execute("alter table vm alter column status type status using status::text::status;")
    op.execute("alter table authentication_directory alter column status type status using status::text::status;")
    op.execute("alter table pool alter column status type status using status::text::status;")
    op.execute("alter table controller alter column status type status using status::text::status;")

    # drop the old enum
    op.execute("drop type old_status CASCADE;")
    # set new status
    op.execute("update vm set status = 'RESERVED' where status = 'BAD_AUTH'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update vm set status = 'SERVICE' where status = 'RESERVED'")
    # ### end Alembic commands ###
