"""active_tk_connection_last_interaction_nullable

Revision ID: 3087e24383ee
Revises: ea07231178a6
Create Date: 2020-12-10 10:23:30.228868

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3087e24383ee'
down_revision = 'ea07231178a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_tk_connection', 'last_interaction',
                    existing_type=sa.DateTime(timezone=True), nullable=True, server_default=None)
    op.add_column('active_tk_connection', sa.Column('disconnected', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('truncate table active_tk_connection;')
    op.alter_column('active_tk_connection', 'last_interaction', existing_type=sa.DateTime(timezone=True),
                    nullable=False, server_default=sa.text('now()'))
    op.drop_column('active_tk_connection', 'disconnected')
    # ### end Alembic commands ###
