"""table_user_favorite_pool

Revision ID: 39d6405e9691
Revises: 4610585ad97d
Create Date: 2022-04-27 11:51:11.675832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39d6405e9691'
down_revision = '4610585ad97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_pool',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('pool_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pool_id', name='user_id_pool_id_unique_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_pool')
    # ### end Alembic commands ###
