"""active_tk_connection_user_id_nullable

Revision ID: 3afef08f92e4
Revises: f650be39c164
Create Date: 2021-06-16 11:10:47.482089

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3afef08f92e4'
down_revision = 'f650be39c164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_tk_connection', 'user_id',
                    existing_type=postgresql.UUID(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE active_tk_connection;")
    op.alter_column('active_tk_connection', 'user_id',
                    existing_type=postgresql.UUID(),
                    nullable=False)
    # ### end Alembic commands ###
