"""Rename_column_ad_cn_pattern.

Revision ID: 3bdd27d82159
Revises: 96d866b36fa2
Create Date: 2021-07-27 17:50:21.984617

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3bdd27d82159"
down_revision = "96d866b36fa2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE automated_pool RENAME COLUMN ad_cn_pattern TO ad_ou")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE automated_pool RENAME COLUMN ad_ou TO ad_cn_pattern")
    # ### end Alembic commands ###
