"""vm_connection_data_table

Revision ID: 4610585ad97d
Revises: 70220709e7b7
Create Date: 2022-03-25 11:09:08.888329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4610585ad97d'
down_revision = '70220709e7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vm_connection_data',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('vm_id', postgresql.UUID(), nullable=False),
                    sa.Column('connection_type',
                              postgresql.ENUM(name="poolconnectiontypes", create_type=False), nullable=False),
                    sa.Column('address', sa.Unicode(length=128), nullable=False),
                    sa.Column('port', sa.Integer(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm_connection_data')
    # ### end Alembic commands ###
