"""Task add column creator

Revision ID: 5ef78c64c084
Revises: a31gh528cv4f
Create Date: 2021-12-01 15:59:45.968139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ef78c64c084'
down_revision = 'a31gh528cv4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('creator', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'creator')
    # ### end Alembic commands ###
