"""create_table_rds_pool

Revision ID: 5f6ebf8486ec
Revises: e413a330f712
Create Date: 2021-04-29 15:10:22.091782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f6ebf8486ec'
down_revision = 'e413a330f712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rds_pool',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['pool.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )

    op.drop_index('ix_tk_connection_statistics_conn_id', table_name='tk_connection_statistics')
    op.drop_table('tk_connection_statistics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tk_connection_statistics',
                    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('conn_id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('avg_rtt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('loss_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('max_rtt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('min_rtt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('read_speed', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('received', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.Column('write_speed', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['conn_id'], ['active_tk_connection.id'], name='tk_connection_statistics_conn_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='tk_connection_statistics_pkey')
                    )
    op.create_index('ix_tk_connection_statistics_conn_id', 'tk_connection_statistics', ['conn_id'], unique=False)

    op.drop_table('rds_pool')
    # ### end Alembic commands ###
