"""Tags_field_for_pools

Revision ID: 80d82b9cbd8a
Revises: ef39174d595c
Create Date: 2021-02-02 12:19:23.376044

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '80d82b9cbd8a'
down_revision = 'ef39174d595c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE pool ADD COLUMN IF NOT EXISTS tag uuid;")
    op.alter_column('pool', 'tag', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'tag')
    # ### end Alembic commands ###
