"""empty message

Revision ID: 836f611f1cab
Revises: 9277751c9fcb
Create Date: 2020-07-16 17:38:10.136053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836f611f1cab'
down_revision = '9277751c9fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('ad_cn', sa.Unicode(length=1000), nullable=True))
    op.create_unique_constraint(None, 'group', ['ad_cn'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='unique')
    op.drop_column('group', 'ad_cn')
    # ### end Alembic commands ###
