"""2fa_auth.

Revision ID: 96d866b36fa2
Revises: c2bd639f503d
Create Date: 2021-07-21 13:34:31.453747

"""
from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "96d866b36fa2"
down_revision = "c2bd639f503d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("two_factor", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("secret", sa.String(), nullable=True))
    op.execute("""update public.user set two_factor = False""")
    op.alter_column("user", "two_factor",
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "two_factor")
    op.drop_column("user", "secret")
    # ### end Alembic commands ###
