"""Cache_field_settings.

Revision ID: 9d14f7f75d65
Revises: 5ef78c64c084
Create Date: 2021-12-17 12:17:08.536707

"""
import json

from alembic import op

# revision identifiers, used by Alembic.
revision = "9d14f7f75d65"
down_revision = "5ef78c64c084"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    settings_dict = {"LANGUAGE": "ru",
                     "DEBUG": False,
                     "REDIS_EXPIRE_TIME": 600,
                     "VEIL_CACHE_TTL": 1,
                     "VEIL_CACHE_SERVER": "localhost",
                     "VEIL_CACHE_PORT": 11211,
                     "VEIL_REQUEST_TIMEOUT": 15,
                     "VEIL_CONNECTION_TIMEOUT": 15,
                     "VEIL_GUEST_AGENT_EXTRA_WAITING": 3,
                     "VEIL_OPERATION_WAITING": 10,
                     "VEIL_MAX_BODY_SIZE": 1000 * 1024 ^ 3,
                     "VEIL_MAX_CLIENTS": 10,
                     "VEIL_SSL_ON": False,
                     "VEIL_WS_MAX_TIME_TO_WAIT": 60,
                     "VEIL_VM_PREPARE_TIMEOUT": 1200.0,
                     "VEIL_MAX_URL_LEN": 6000,
                     "VEIL_MAX_IDS_LEN": 3780,
                     "VEIL_MAX_VM_CREATE_ATTEMPTS": 10
                     }
    settings_json = json.dumps(settings_dict)
    op.execute("UPDATE journal_settings SET by_count = false WHERE by_count = true")
    op.execute(
        """UPDATE public.settings SET settings = '{}'""".format(settings_json))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    settings_dict = {"LANGUAGE": "ru",
                     "DEBUG": False,
                     "VEIL_CACHE_TTL": 1,
                     "VEIL_CACHE_SERVER": "localhost",
                     "VEIL_CACHE_PORT": 11211,
                     "VEIL_REQUEST_TIMEOUT": 15,
                     "VEIL_CONNECTION_TIMEOUT": 15,
                     "VEIL_GUEST_AGENT_EXTRA_WAITING": 3,
                     "VEIL_OPERATION_WAITING": 10,
                     "VEIL_MAX_BODY_SIZE": 1000 * 1024 ^ 3,
                     "VEIL_MAX_CLIENTS": 10,
                     "VEIL_SSL_ON": False,
                     "VEIL_WS_MAX_TIME_TO_WAIT": 60,
                     "VEIL_VM_PREPARE_TIMEOUT": 1200.0,
                     "VEIL_MAX_URL_LEN": 6000,
                     "VEIL_MAX_IDS_LEN": 3780,
                     "VEIL_MAX_VM_CREATE_ATTEMPTS": 10
                     }
    settings_json = json.dumps(settings_dict)
    op.execute(
        """UPDATE public.settings SET settings = '{}'""".format(settings_json))
    # ### end Alembic commands ###
