"""ActiveTkConnection_add_new_columns

Revision ID: a2769e628235
Revises: 07972ddc0722
Create Date: 2021-03-26 14:58:09.268050

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a2769e628235'
down_revision = '07972ddc0722'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('active_tk_connection',
                  sa.Column('connection_type', sa.Enum('SPICE', 'SPICE_DIRECT', 'RDP', 'NATIVE_RDP',
                                                       name='poolconnectiontypes'), nullable=True))

    op.add_column('active_tk_connection', sa.Column('is_connection_secure', sa.Boolean(), nullable=True))
    op.execute('UPDATE active_tk_connection SET is_connection_secure = false')
    op.alter_column(table_name='active_tk_connection', column_name='is_connection_secure', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_tk_connection', 'is_connection_secure')
    op.drop_column('active_tk_connection', 'connection_type')
    # ### end Alembic commands ###
