"""create table tk_vm_connection

Revision ID: a3da31776be8
Revises: 17997eb1f91f
Create Date: 2022-01-25 15:52:32.630384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3da31776be8'
down_revision = '17997eb1f91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tk_vm_connection',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('tk_connection_id', postgresql.UUID(), nullable=False),
                    sa.Column('successful', sa.Boolean(), nullable=False),
                    sa.Column('conn_error_str', sa.Unicode(), nullable=True),
                    sa.Column('vm_id', postgresql.UUID(), nullable=False),
                    sa.Column('connected_to_vm', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('disconnected_from_vm', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('connection_type',
                              postgresql.ENUM(name='poolconnectiontypes', create_type=False),
                              nullable=True),
                    sa.Column('is_connection_secure', sa.Boolean(), nullable=True),
                    sa.Column('read_speed', sa.Integer(), nullable=True),
                    sa.Column('write_speed', sa.Integer(), nullable=True),
                    sa.Column('avg_rtt', sa.Float(), nullable=True),
                    sa.Column('loss_percentage', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['tk_connection_id'], ['active_tk_connection.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.drop_column('active_tk_connection', 'is_connection_secure')
    op.drop_column('active_tk_connection', 'avg_rtt')
    op.drop_column('active_tk_connection', 'read_speed')
    op.drop_column('active_tk_connection', 'loss_percentage')
    op.drop_column('active_tk_connection', 'connection_type')
    op.drop_column('active_tk_connection', 'write_speed')
    op.drop_column('active_tk_connection', 'vm_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_tk_connection', sa.Column('vm_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('active_tk_connection', sa.Column('write_speed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('active_tk_connection', sa.Column('connection_type',
                                                    postgresql.ENUM(name='poolconnectiontypes', create_type=False),
                                                    autoincrement=False, nullable=True))
    op.add_column('active_tk_connection',
                  sa.Column('loss_percentage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('active_tk_connection', sa.Column('read_speed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('active_tk_connection',
                  sa.Column('avg_rtt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('active_tk_connection',
                  sa.Column('is_connection_secure', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.drop_table('tk_vm_connection')
    # ### end Alembic commands ###
