"""Pool created updated  creator

Revision ID: a73bdb4c3e7a
Revises: d975fd61c002
Create Date: 2022-07-06 10:07:49.220852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a73bdb4c3e7a'
down_revision = 'd975fd61c002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                                    nullable=True))
    op.add_column('pool', sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                                    nullable=True))
    op.add_column('pool', sa.Column('creator', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'creator')
    op.drop_column('pool', 'updated')
    op.drop_column('pool', 'created')
    # ### end Alembic commands ###
