"""smtp_settings.

Revision ID: c2bd639f503d
Revises: 0bdf794ff5ef
Create Date: 2021-07-09 16:38:59.499347

"""
import json

from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c2bd639f503d"
down_revision = "0bdf794ff5ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings",
                  sa.Column("smtp_settings", sa.JSON, nullable=True))
    smtp_dict = {"TLS": False,
                 "SSL": False,
                 "hostname": None,
                 "port": 25,
                 "password": None,
                 "user": None,
                 "from_address": None,
                 "level": 4
                 }
    smtp_json = json.dumps(smtp_dict)
    op.execute(
        """UPDATE public.settings SET smtp_settings = '{}'""".format(smtp_json))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "smtp_settings")
    # ### end Alembic commands ###
