"""License in db

Revision ID: d975fd61c002
Revises: 2a4bec3a23d3
Create Date: 2022-06-22 11:16:04.115081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd975fd61c002'
down_revision = '2a4bec3a23d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('verbose_name', sa.Unicode(length=256), nullable=True),
    sa.Column('thin_clients_limit', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('support_expiration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('company', sa.Unicode(length=256), nullable=True),
    sa.Column('email', sa.Unicode(length=256), nullable=True),
    sa.Column('date_format', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license')
    # ### end Alembic commands ###
