"""tk_conn_network_stats.

Revision ID: db03830bd828
Revises: a2769e628235
Create Date: 2021-04-13 13:06:02.270234

"""
from alembic import op

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "db03830bd828"
down_revision = "a2769e628235"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("active_tk_connection", sa.Column("avg_rtt", sa.Float(), nullable=True))
    op.add_column("active_tk_connection", sa.Column("loss_percentage", sa.Integer(), nullable=True))
    op.add_column("active_tk_connection", sa.Column("read_speed", sa.Integer(), nullable=True))
    op.add_column("active_tk_connection", sa.Column("write_speed", sa.Integer(), nullable=True))

    op.execute("TRUNCATE TABLE tk_connection_statistics;")
    op.add_column("tk_connection_statistics", sa.Column("avg_rtt", sa.Float(), nullable=True))
    op.add_column("tk_connection_statistics", sa.Column("loss_percentage", sa.Integer(), nullable=True))
    op.add_column("tk_connection_statistics", sa.Column("max_rtt", sa.Float(), nullable=True))
    op.add_column("tk_connection_statistics", sa.Column("min_rtt", sa.Float(), nullable=True))
    op.add_column("tk_connection_statistics", sa.Column("read_speed", sa.Integer(), nullable=True))
    op.add_column("tk_connection_statistics", sa.Column("received", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                                                        nullable=False))
    op.add_column("tk_connection_statistics", sa.Column("write_speed", sa.Integer(), nullable=True))
    op.drop_column("tk_connection_statistics", "message")
    op.drop_column("tk_connection_statistics", "created")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE tk_connection_statistics;")
    op.add_column("tk_connection_statistics", sa.Column("created", postgresql.TIMESTAMP(timezone=True),
                                                        server_default=sa.text("now()"), autoincrement=False, nullable=False))
    op.add_column("tk_connection_statistics", sa.Column("message", sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column("tk_connection_statistics", "write_speed")
    op.drop_column("tk_connection_statistics", "received")
    op.drop_column("tk_connection_statistics", "read_speed")
    op.drop_column("tk_connection_statistics", "min_rtt")
    op.drop_column("tk_connection_statistics", "max_rtt")
    op.drop_column("tk_connection_statistics", "loss_percentage")
    op.drop_column("tk_connection_statistics", "avg_rtt")

    op.drop_column("active_tk_connection", "write_speed")
    op.drop_column("active_tk_connection", "read_speed")
    op.drop_column("active_tk_connection", "loss_percentage")
    op.drop_column("active_tk_connection", "avg_rtt")
    # ### end Alembic commands ###
