"""Guest_pools.

Revision ID: e413a330f712
Revises: 07972ddc0722
Create Date: 2021-03-24 17:50:21.984617

"""
from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e413a330f712"
down_revision = "db03830bd828"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("automated_pool", sa.Column("is_guest", sa.Boolean(), nullable=True))
    op.execute("""update public.automated_pool set is_guest = False""")
    op.alter_column("automated_pool", "is_guest",
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("automated_pool", "is_guest")
    # ### end Alembic commands ###
