"""active_tk_connection_drop_user_id_unique

Revision ID: ea07231178a6
Revises: 40932ab2f84c
Create Date: 2020-12-08 12:40:12.689428

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ea07231178a6'
down_revision = '40932ab2f84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('active_tk_connection_user_id_key', 'active_tk_connection', type_='unique')
    op.add_column('active_tk_connection', sa.Column('last_interaction', sa.DateTime(timezone=True),
                                                    nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('active_tk_connection_user_id_key', 'active_tk_connection', ['user_id'])
    op.drop_column('active_tk_connection', 'last_interaction')
    # ### end Alembic commands ###
