"""Using_resource_pools

Revision ID: ef39174d595c
Revises: 969d9b36df65
Create Date: 2020-12-17 17:29:29.716389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef39174d595c'
down_revision = '52224f9ec674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'cluster_id')
    op.drop_column('pool', 'datapool_id')
    op.drop_column('pool', 'node_id')
    op.add_column('pool', sa.Column('resource_pool_id', postgresql.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('cluster_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('pool', sa.Column('datapool_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('pool', sa.Column('node_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('pool', 'resource_pool_id')
    # ### end Alembic commands ###
