"""Using_resource_pools

Revision ID: ef39174d595c
Revises: 969d9b36df65
Create Date: 2020-12-17 17:29:29.716389

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ef39174d595c'
down_revision = '52224f9ec674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pool', 'cluster_id', nullable=True)
    op.alter_column('pool', 'datapool_id', nullable=True)
    op.alter_column('pool', 'node_id', nullable=True)
    op.execute("ALTER TABLE pool ADD COLUMN IF NOT EXISTS resource_pool_id uuid;")
    op.alter_column('pool', 'resource_pool_id', nullable=True)
    op.execute("""update pool set status ='ACTIVE' where pool.resource_pool_id IS NOT NULL""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""update pool set status ='FAILED' where pool.resource_pool_id IS NOT NULL""")
    # ### end Alembic commands ###
