"""ad_user_fields.

Revision ID: f8b9f6b669a9
Revises: 3bdd27d82159
Create Date: 2021-08-05 15:22:50.440893

"""
from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f8b9f6b669a9"
down_revision = "3bdd27d82159"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("local_password", sa.Boolean(), nullable=True))
    op.execute("""update public.user set local_password = False""")
    op.execute("""update public.user set local_password = True where password like 'pbkdf2_sha256%'""")
    op.alter_column("user", "local_password",
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.add_column("user", sa.Column("by_ad", sa.Boolean(), nullable=True))
    op.execute("""update public.user set by_ad = False""")
    op.execute("""update public.user set by_ad = True where local_password = False""")
    op.alter_column("user", "by_ad",
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "by_ad")
    op.drop_column("user", "local_password")
    # ### end Alembic commands ###
