---

- name: Install redis-server
  apt:
    name: redis-server
    state: latest
    update_cache: yes

- name: Enable service redis-server
  service:
    name: redis-server
    enabled: yes

- name: Configure redis.conf
  template:
    src: redis.conf.j2
    dest: "/etc/redis/redis.conf"
    owner: redis
    group: redis
    mode: 0640
  notify:
    - restart redis-server

- name: Insert redis-server password
  lineinfile:
    path: /etc/redis/redis.conf
    insertafter: EOF
    line: "requirepass {{ redis-server_password }}"
  notify:
    - restart redis-server