---

- name: Deploy VeiL Broker
  hosts: broker
  become: true
  any_errors_fatal: true
  gather_facts: true
  vars:
    minimal_ansible_version: 2.7.0
  tasks:
    - name: Checking OS
      fail:
        msg: "OS must be Astra Linux SE 1.7"
      when: ansible_lsb.description != 'Astra Linux 1.7 x86-64'

    - name: Checking ansible version
      fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      when: ansible_version.full is version(minimal_ansible_version, '<')

    - include_role:
        name: smolensk

    - include_role:
        name: broker
      when: broker_mode is not defined

    - include_role:
        name: multibroker
      when: broker_mode is defined and broker_mode  == "multi"