---
# yamllint disable rule:line-length

- hosts: broker
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  vars_files:
    - vars/main.yml
    - vars/pgcluster.yml
    - vars/system.yml
    - "vars/{{ ansible_os_family }}.yml"
  roles:
    - role: smolensk
      when: ansible_os_family == "Astra Linux"

    - role: resolv_conf
    - role: timezone
    - role: ntp

    - role: broker

...
