---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - system

- hosts: all
  roles:
    - smolensk

- hosts: databases
  roles:
    - postgres
  tags: pg

- hosts: databases
  roles:
    - 2ndquadrant
    - repmgr
  tags: repmgr

- hosts: backups
  roles:
    - postgres
    - repmgrd
  tags: repmgrd

- hosts: backups
  roles:
    - repmgrd_ha
  tags: repmgrd_ha

- hosts: backups
  roles:
    - barman
  tags: barman
