---

- name: Deploy VeiL Broker and PostgreSQL HA Cluster (based on "Patroni" and "{{ dcs_type }}")
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml
    - vars/pgcluster.yml
  vars:
    minimal_ansible_version: 2.7.0
  tasks:
    - name: Checking ansible version
      fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      when: ansible_version.full is version(minimal_ansible_version, '<')

- import_playbook: deploy_pgcluster.yml
  when: with_pgcluster|bool
  tags: pgcluster

- import_playbook: deploy_broker.yml
  when: with_broker|bool and not broker_exists|bool
  tags: broker