# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do | config |

    config.vm.provider "libvirt"
    config.vm.box_check_update = false


    controller_box = "veil-controller-dev"
    controller_box_url = "http://192.168.10.144/veil_vagrant/veil-controller-dev.json"



    config.vm.define "vdi_host" do | vdi_host |
        
        # vdi_host.vm.synced_folder "./../../", "/opt/veil-vdi", type: "nfs", nfs_version: "3", nfs_udp: false, \
                                            # mount_options: ["rw", "tcp", "nolock", "noacl", "async"]
        vdi_host.vm.synced_folder './../../', '/opt/veil-vdi', type: "rsync", owner: "vagrant", group: "vagrant"
#        vdi_host.vm.synced_folder './../../backend', '/opt/veil-vdi/backend', type: "rsync", owner: "vagrant", group: "vagrant"
        vdi_host.vm.network "private_network", ip: "192.168.20.112"
        vdi_host.vm.provision :shell, path: "./vdi-deploy.sh", privileged: true
        vdi_host.vm.provision :shell, path: "./veil-provision.sh", privileged: true
        vdi_host.ssh.password = "vagrant"
        
        vdi_host.vm.box = "generic/debian9"
        vdi_host.vm.hostname = "vdihost"
    
        vdi_host.vm.provider "libvirt" do | libvirt |
            libvirt.cpus = 2
            libvirt.memory = 1024*2
        end
    end
end