---

- name: Install ansible dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ postgresql_system_packages_list }}"

- name: Install postgresql
  apt:
    name: "postgresql-{{ postgresql_version }}"
    update_cache: yes

- name: Configure postgresql
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_conf_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify:
    - restart postgresql

- name: Create db user
  postgresql_user:
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_pass }}"
    role_attr_flags: LOGIN,SUPERUSER
  no_log: true
  become: true
  become_user: postgres

- name: Create database
  postgresql_db:
    name: "{{ postgresql_db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    owner: "{{ postgresql_db_user }}"
  become: true
  become_user: postgres

- name: Create db extension
  postgresql_ext:
    name: "{{ item }}"
    db: "{{ postgresql_db_name }}"
  become: true
  become_user: postgres
  loop: "{{ postgresql_pg_ext_list }}"