---

- name: Install postgresql
  apt:
    name: postgresql
    state: latest
    update_cache: yes

- name: Configure postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    owner: {{ postgresql_system_user }}
    group: {{ postgresql_system_user }}
    mode: 0644
  notify:
    - restart postgresql

- name: Configure pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: {{ postgresql_system_user }}
    group: {{ postgresql_system_user }}
    mode: 0640
  notify:
    - restart postgresql
  when: {{ postgresql_replica }}

- name: Locale fix
  command: "localedef -i en_US -f UTF-8 en_US.UTF-8"

- name: Configure system user
  user:
    name: {{ postgresql_system_user }}
    password: {{ postgresql_system_user_password }}

- name: Configure postgres role
  postgresql_user:
    user: {{ postgresql_db_role }}
    password: {{ postgresql_db_password }}
  become: yes
  become_user: {{ postgresql_system_user }}

- name: Create replication role
  postgresql_user:
    name: "{{ postgresql_repl_role }}"
    password: "{{ postgresql_repl_role_password }}"
    role_attr_flags: replication
  become: yes
  become_user: {{ postgresql_system_user }}
  when: {{ postgresql_replica }}

- name: Create postgresql db
  postgresql_db:
    name: {{ postgresql_db_name }}
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: yes
  become_user: {{ postgresql_system_user }}