---

- name: Repmgrd_HA | update repmgrd config
  blockinfile:
    dest: "{{ repmgrd_config }}"
    block: "{{ lookup('template', 'repmgrd.conf.j2') }}"
    insertbefore: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR REPMGRD_HA"

- name: Repmgrd_HA | restart repmgrd
  service:
    name: "{{ repmgrd_base }}"
    state: restarted
    enabled: yes
