---
# yamllint disable rule:line-length

- block:  # Debian/Ubuntu
    - name: Add repository apt-key
      apt_key:
        url: "{{ item.key }}"
        state: present
      loop: "{{ apt_repository_keys }}"
      when: apt_repository_keys | length > 0

    - name: Add repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: present
        update_cache: true
      loop: "{{ apt_repository }}"
      when: apt_repository | length > 0
  environment: "{{ proxy_env | default({}) }}"
  when: installation_method == "repo" and ansible_os_family == "Debian"
  tags: add_repo

- block:  # RedHat/CentOS
    - name: Add repository
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgkey: "{{ item.gpgkey }}"
        gpgcheck: "{{ item.gpgcheck }}"
      loop: "{{ yum_repository | flatten(1) }}"
      when: yum_repository | length > 0

    # Install Epel Repository
    - name: Remove epel-release package (if exists)
      package:
        name: epel-release
        state: absent
      when: install_epel_repo|bool
      tags: install_epel_repo

    - name: Get epel-release-latest rpm package
      get_url:
        url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"  # noqa 204
        dest: /tmp/
        timeout: 30
        validate_certs: false
      when: install_epel_repo|bool
      tags: install_epel_repo

    - name: Install EPEL repository
      package:
        name: "/tmp/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true
      when: install_epel_repo|bool
      tags: install_epel_repo

    # Install SCL Repository
    - name: Install Software Collections (SCL) repository for CentOS 7
      package:
        name: centos-release-scl-rh
        state: present
      when: install_scl_repo|bool and
            (ansible_distribution == 'CentOS' and
            ansible_distribution_major_version == '7')
      tags: install_scl_repo

    - name: Install Software Collections (SCL) repository for OracleLinux 7
      yum_repository:
        name: ol7_software_collections
        description: Software Collection Library packages for Oracle Linux 7 (x86_64)
        baseurl: https://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
        gpgcheck: true
        enabled: true
      when: install_scl_repo|bool and
            (ansible_distribution == "OracleLinux" and
            ansible_distribution_major_version == '7')
      tags: install_scl_repo

    - name: Enable Software Collections (SCL) repository for RedHat 7
      become: true
      become_user: root
      command: subscription-manager repos --enable rhel-server-rhscl-7-rpms
      when: install_scl_repo|bool and
            (ansible_distribution == 'RedHat' and
            ansible_distribution_major_version == '7')
      tags: install_scl_repo

    # Install PostgreSQL Repository
    - name: Get pgdg-redhat-repo-latest.noarch.rpm
      get_url:
        url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"  # noqa 204
        dest: /tmp/
        timeout: 30
        validate_certs: false
      when: install_postgresql_repo|bool
      tags: install_postgresql_repo

    - name: Install PostgreSQL repository
      package:
        name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
        state: present
        disable_gpg_check: true
      when: install_postgresql_repo|bool
      tags: install_postgresql_repo
  environment: "{{ proxy_env | default({}) }}"
  when: installation_method == "repo" and ansible_os_family == "RedHat"
  tags: add_repo

...
