---

broker_db_name: "vdi"
broker_db_user: "vdi"
broker_local_settings: "/opt/veil-vdi/app/common/local_settings.py"
broker_apt_repo: "deb [trusted=yes] file:///media/cdrom/repo smolensk main"

broker_system_packages_list:
  - python3
  - python3-apt
  - python3-psycopg2

broker_packages_list:
  - veil-broker-frontend
  - veil-broker-docs
  - veil-broker-backend

broker_services_list:
  - vdi-web
  - vdi-pool_worker
  - vdi-monitor_worker

broker_pg_ext_list: [uuid-ossp]
