---

broker_postgresql_version: "11"
broker_postgresql_cluster_name: "main"
broker_postgresql_conf_dir: "/etc/postgresql/{{ broker_postgresql_version }}/{{ broker_postgresql_cluster_name }}"
broker_db_name: "vdi"
broker_db_user: "vdi"

broker_local_settings: "/opt/veil-vdi/app/common/local_settings.py"
broker_apt_repo: "deb [trusted=yes] file:///media/cdrom/repo 1.7_x86-64 main"

broker_system_packages_list:
  - python3
  - python3-apt
  - python3-psycopg2

broker_packages_list:
  - veil-broker-frontend
  - veil-broker-docs
  - veil-broker-backend
  - veil-connect-web

broker_services_list:
  - vdi-web
  - vdi-pool_worker
  - vdi-monitor_worker

broker_pg_ext_list: [uuid-ossp]

broker_guacamole_packages_list:
  - guacd
  - libguac-client-rdp0
  - libguac-client-ssh0
  - libguac-client-telnet0
  - libguac-client-vnc0
