"""Add EventReadByUser table

Revision ID: 20e197310113
Revises: bf78d2d3b5ef
Create Date: 2019-12-19 18:42:33.537058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20e197310113'
down_revision = 'bf78d2d3b5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_read_by_user',
    sa.Column('event', postgresql.UUID(), nullable=False),
    sa.Column('user', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_read_by_user')
    # ### end Alembic commands ###
