"""empty message

Revision ID: 24e40621a8f8
Revises: c82fb00107a7
Create Date: 2020-03-04 13:43:37.513285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24e40621a8f8'
down_revision = 'c82fb00107a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('user_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'vm', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vm', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vm', type_='foreignkey')
    op.drop_column('vm', 'user_id')
    # ### end Alembic commands ###
