"""pool table change structure v2

Revision ID: 27386d7871d2
Revises: cc4dfc473fb6
Create Date: 2019-11-14 11:56:39.272930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27386d7871d2'
down_revision = 'cc4dfc473fb6'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("DROP TYPE status CASCADE;")
    # op.execute(
    #     "CREATE TYPE status AS ENUM ('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL', 'BAD_AUTH');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('pool_id', postgresql.UUID(), nullable=False),
    sa.Column('verbose_name', sa.Unicode(length=128), nullable=False),
    sa.Column('cluster_id', postgresql.UUID(), nullable=False),
    sa.Column('node_id', postgresql.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATING', 'ACTIVE', 'FAILED', 'DELETING', 'SERVICE', 'PARTIAL', 'BAD_AUTH', name='status'), nullable=False),
    sa.Column('controller', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['controller'], ['controller.id'], ),
    sa.PrimaryKeyConstraint('pool_id'),
    sa.UniqueConstraint('verbose_name')
    )
    op.create_index(op.f('ix_pool_status'), 'pool', ['status'], unique=False)
    op.create_table('automated_pool',
    sa.Column('automated_pool_id', postgresql.UUID(), nullable=False),
    sa.Column('datapool_id', postgresql.UUID(), nullable=False),
    sa.Column('template_id', postgresql.UUID(), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('max_vm_amount', sa.Integer(), nullable=False),
    sa.Column('increase_step', sa.Integer(), nullable=False),
    sa.Column('max_amount_of_create_attempts', sa.Integer(), nullable=False),
    sa.Column('initial_size', sa.Integer(), nullable=False),
    sa.Column('reserve_size', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('vm_name_template', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['automated_pool_id'], ['pool.pool_id'], ),
    sa.PrimaryKeyConstraint('automated_pool_id')
    )
    op.create_table('pools_users',
    sa.Column('pool_id', postgresql.UUID(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.pool_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('static_pool',
    sa.Column('static_pool_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['static_pool_id'], ['pool.pool_id'], ),
    sa.PrimaryKeyConstraint('static_pool_id')
    )
    op.create_table('vm',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('template_id', sa.Unicode(length=100), nullable=True),
    sa.Column('pool_id', postgresql.UUID(), nullable=True),
    sa.Column('username', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.pool_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm')
    op.drop_table('static_pool')
    op.drop_table('pools_users')
    op.drop_table('automated_pool')
    op.drop_index(op.f('ix_pool_status'), table_name='pool')
    op.drop_table('pool')
    # ### end Alembic commands ###
    # op.execute("DROP TYPE status CASCADE;")