"""empty message

Revision ID: 2a37a0ca8641
Revises: 6fac9bacc0ab
Create Date: 2020-01-29 13:44:30.659379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a37a0ca8641'
down_revision = '6fac9bacc0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('broken', sa.Boolean(), nullable=True))
    op.execute('UPDATE vm set broken = false;')
    op.alter_column('vm', 'broken', existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm', 'broken')
    # ### end Alembic commands ###
