"""empty message

Revision ID: 2adb26d437a6
Revises: 710d71b384ba
Create Date: 2020-02-25 14:42:20.939830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2adb26d437a6'
down_revision = '710d71b384ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_role_owner_entity_role_group', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_group', 'entity_role_owner', ['id', 'role', 'group_id'], unique=True)
    op.drop_index('ix_entity_role_owner_entity_role_owner', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_owner', 'entity_role_owner', ['id', 'role', 'group_id', 'user_id'], unique=True)
    op.drop_index('ix_entity_role_owner_entity_role_user', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_user', 'entity_role_owner', ['id', 'role', 'user_id'], unique=True)
    op.create_unique_constraint(None, 'entity_role_owner', ['id'])
    op.drop_constraint('entity_role_owner_entity_id_fkey', 'entity_role_owner', type_='foreignkey')
    op.create_foreign_key(None, 'entity_role_owner', 'entity', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('entity_role_owner', 'entity_id')
    op.create_index('ix_entity_entity_object_entity_type', 'entity', ['entity_uuid', 'entity_type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_entity_object_entity_type', table_name='entity')
    op.add_column('entity_role_owner', sa.Column('entity_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'entity_role_owner', type_='foreignkey')
    op.create_foreign_key('entity_role_owner_entity_id_fkey', 'entity_role_owner', 'entity', ['entity_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'entity_role_owner', type_='unique')
    op.drop_index('ix_entity_role_owner_entity_role_user', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_user', 'entity_role_owner', ['entity_id', 'role', 'user_id'], unique=True)
    op.drop_index('ix_entity_role_owner_entity_role_owner', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_owner', 'entity_role_owner', ['entity_id', 'role', 'group_id', 'user_id'], unique=True)
    op.drop_index('ix_entity_role_owner_entity_role_group', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_group', 'entity_role_owner', ['entity_id', 'role', 'group_id'], unique=True)
    # ### end Alembic commands ###
