"""empty message

Revision ID: 2f9e205cd01e
Revises: 3842510e083b
Create Date: 2020-01-27 18:55:38.803782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9e205cd01e'
down_revision = '3842510e083b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('created_by_vdi', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm', 'created_by_vdi')
    # ### end Alembic commands ###
