"""Entity owners

Revision ID: 710d71b384ba
Revises: 813ca10a8187
Create Date: 2020-02-18 14:57:18.222537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '710d71b384ba'
down_revision = '813ca10a8187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_role_owner',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('entity_id', postgresql.UUID(), nullable=True),
                    sa.Column('role',
                              sa.Enum('READ_ONLY', 'ADMINISTRATOR', 'SECURITY_ADMINISTRATOR', 'VM_ADMINISTRATOR',
                                      'NETWORK_ADMINISTRATOR', 'STORAGE_ADMINISTRATOR', 'VM_OPERATOR', name='role'),
                              nullable=True),
                    sa.Column('user_id', postgresql.UUID(), nullable=True),
                    sa.Column('group_id', postgresql.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_entity_role_owner_entity_role_group', 'entity_role_owner', ['entity_id', 'role', 'group_id'], unique=True)
    op.create_index('ix_entity_role_owner_entity_role_owner', 'entity_role_owner', ['entity_id', 'role', 'group_id', 'user_id'], unique=True)
    op.create_index('ix_entity_role_owner_entity_role_user', 'entity_role_owner', ['entity_id', 'role', 'user_id'], unique=True)
    op.create_index(op.f('ix_entity_role_owner_role'), 'entity_role_owner', ['role'], unique=False)
    op.drop_index('ix_role_entity_permission_permission', table_name='role_entity_permission')
    op.drop_index('ix_role_entity_permission_role', table_name='role_entity_permission')
    op.drop_index('ix_role_entity_permission_role_entity_permission', table_name='role_entity_permission')
    op.drop_table('role_entity_permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity', 'entity_type',
                    existing_type=sa.Enum('ANGLUAR', 'THIN_CLIENT', 'CONTROLLER', 'SECURITY', 'POOL',
                                          name='entitytype'),
                    type_=sa.VARCHAR(),
                    nullable=True)
    op.create_table('role_entity_permission',
                    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('permission', postgresql.ENUM('VIEW', 'ADD', 'CHANGE', 'DELETE', name='permission'),
                              autoincrement=False, nullable=False),
                    sa.Column('role', postgresql.ENUM('READ_ONLY', 'ADMINISTRATOR', 'SECURITY_ADMINISTRATOR',
                                                      'VM_ADMINISTRATOR', 'NETWORK_ADMINISTRATOR',
                                                      'STORAGE_ADMINISTRATOR', 'VM_OPERATOR', name='role'),
                              autoincrement=False, nullable=False),
                    sa.Column('entity_id', postgresql.UUID(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name='role_entity_permission_entity_id_fkey',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='role_entity_permission_pkey')
                    )
    op.create_index('ix_role_entity_permission_role_entity_permission', 'role_entity_permission', ['permission', 'role', 'entity_id'], unique=True)
    op.create_index('ix_role_entity_permission_role', 'role_entity_permission', ['role'], unique=False)
    op.create_index('ix_role_entity_permission_permission', 'role_entity_permission', ['permission'], unique=False)
    op.drop_index(op.f('ix_entity_role_owner_role'), table_name='entity_role_owner')
    op.drop_index('ix_entity_role_owner_entity_role_user', table_name='entity_role_owner')
    op.drop_index('ix_entity_role_owner_entity_role_owner', table_name='entity_role_owner')
    op.drop_index('ix_entity_role_owner_entity_role_group', table_name='entity_role_owner')
    op.drop_table('entity_role_owner')
    # ### end Alembic commands ###
