"""pool_pk_changed_to_id

Revision ID: 7620b34953b9
Revises: e9bd2522cefd
Create Date: 2020-01-09 20:41:14.903123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7620b34953b9'
down_revision = 'e9bd2522cefd'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('truncate table pool cascade;')

    op.drop_constraint('automated_pool_automated_pool_id_fkey', 'automated_pool', type_='foreignkey')
    op.drop_constraint('static_pool_static_pool_id_fkey', 'static_pool', type_='foreignkey')
    op.drop_constraint('vm_pool_id_fkey', 'vm', type_='foreignkey')
    op.drop_constraint('pools_users_pool_id_fkey', 'pools_users', type_='foreignkey')

    op.drop_column('static_pool', 'static_pool_id')
    op.drop_column('automated_pool', 'automated_pool_id')
    op.drop_column('pool', 'pool_id')

    op.add_column('pool', sa.Column('id', postgresql.UUID(), nullable=False))
    op.add_column('automated_pool', sa.Column('id', postgresql.UUID(), nullable=False))
    op.add_column('static_pool', sa.Column('id', postgresql.UUID(), nullable=False))

    op.create_unique_constraint(None, 'pool', ['id'])
    op.create_unique_constraint(None, 'static_pool', ['id'])
    op.create_unique_constraint(None, 'automated_pool', ['id'])
    op.create_unique_constraint(None, 'pools_users', ['pool_id'])
    op.create_unique_constraint(None, 'vm', ['pool_id'])

    op.create_foreign_key('static_pool_static_pool_id_fkey', 'static_pool', 'pool', ['id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('automated_pool_automated_pool_id_fkey', 'automated_pool', 'pool', ['id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('pools_users_pool_id_fkey', 'pools_users', 'pool', ['pool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('vm_pool_id_fkey', 'vm', 'pool', ['pool_id'], ['id'], ondelete='CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vm', type_='foreignkey')
    op.create_foreign_key('vm_pool_id_fkey', 'vm', 'pool', ['pool_id'], ['pool_id'], ondelete='CASCADE')
    op.add_column('static_pool', sa.Column('static_pool_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'static_pool', type_='foreignkey')
    op.create_foreign_key('static_pool_static_pool_id_fkey', 'static_pool', 'pool', ['static_pool_id'], ['pool_id'], ondelete='CASCADE')
    op.drop_column('static_pool', 'id')
    op.drop_constraint(None, 'pools_users', type_='foreignkey')
    op.create_foreign_key('pools_users_pool_id_fkey', 'pools_users', 'pool', ['pool_id'], ['pool_id'], ondelete='CASCADE')
    op.add_column('pool', sa.Column('pool_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('pool', 'id')
    op.add_column('automated_pool', sa.Column('automated_pool_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'automated_pool', type_='foreignkey')
    op.create_foreign_key('automated_pool_automated_pool_id_fkey', 'automated_pool', 'pool', ['automated_pool_id'], ['pool_id'], ondelete='CASCADE')
    op.drop_column('automated_pool', 'id')
    # ### end Alembic commands ###
