"""pool os_type

Revision ID: bf78d2d3b5ef
Revises: f72ec69e9658
Create Date: 2019-12-16 19:08:45.801078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf78d2d3b5ef'
down_revision = 'f72ec69e9658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automated_pool', sa.Column('os_type', sa.Unicode(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automated_pool', 'os_type')
    # ### end Alembic commands ###
