"""empty message

Revision ID: c82fb00107a7
Revises: d78ec13ec459
Create Date: 2020-02-26 20:04:24.376221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c82fb00107a7'
down_revision = 'd78ec13ec459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_role_owner', sa.Column('entity_id', postgresql.UUID(), nullable=True))
    op.drop_index('ix_entity_role_owner_entity_role_group', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_group', 'entity_role_owner', ['entity_id', 'role', 'group_id'], unique=True)
    op.drop_index('ix_entity_role_owner_entity_role_owner', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_owner', 'entity_role_owner', ['entity_id', 'role', 'group_id', 'user_id'], unique=True)
    op.drop_index('ix_entity_role_owner_entity_role_user', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_user', 'entity_role_owner', ['entity_id', 'role', 'user_id'], unique=True)
    op.drop_constraint('entity_role_owner_id_key', 'entity_role_owner', type_='unique')
    op.drop_constraint('entity_role_owner_id_fkey', 'entity_role_owner', type_='foreignkey')
    op.create_foreign_key(None, 'entity_role_owner', 'entity', ['entity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity_role_owner', type_='foreignkey')
    op.create_foreign_key('entity_role_owner_id_fkey', 'entity_role_owner', 'entity', ['id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('entity_role_owner_id_key', 'entity_role_owner', ['id'])
    op.drop_index('ix_entity_role_owner_entity_role_user', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_user', 'entity_role_owner', ['id', 'role', 'user_id'], unique=True)
    op.drop_index('ix_entity_role_owner_entity_role_owner', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_owner', 'entity_role_owner', ['id', 'role', 'group_id', 'user_id'], unique=True)
    op.drop_index('ix_entity_role_owner_entity_role_group', table_name='entity_role_owner')
    op.create_index('ix_entity_role_owner_entity_role_group', 'entity_role_owner', ['id', 'role', 'group_id'], unique=True)
    op.drop_column('entity_role_owner', 'entity_id')
    # ### end Alembic commands ###
