"""empty message

Revision ID: d78ec13ec459
Revises: 2adb26d437a6
Create Date: 2020-02-26 17:06:35.210086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd78ec13ec459'
down_revision = '2adb26d437a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pools_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pools_users',
                    sa.Column('pool_id', postgresql.UUID(), autoincrement=False, nullable=True),
                    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], name='pools_users_pool_id_fkey',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='pools_users_user_id_fkey',
                                            ondelete='CASCADE')
                    )
    # ### end Alembic commands ###
