"""AD Mappings

Revision ID: e1d8cccf33c5
Revises: 190e9f2ff62b
Create Date: 2020-02-11 15:16:02.445408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1d8cccf33c5'
down_revision = '190e9f2ff62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping',
                    sa.Column('description', sa.Unicode(length=255), nullable=True),
                    sa.Column('mapping_type', sa.Enum('USER', 'OU', 'GROUP', name='mappingtypes'), nullable=False),
                    sa.Column('verbose_name', sa.Unicode(length=128), nullable=False),
                    sa.Column('priority', sa.Integer(), nullable=False),
                    sa.UniqueConstraint('verbose_name')
                    )
    op.create_index(op.f('ix_mapping_mapping_type'), 'mapping', ['mapping_type'], unique=False)
    op.create_table('group_authentication_directory_mappings',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('authentication_directory_id', postgresql.UUID(), nullable=False),
                    sa.Column('group_id', postgresql.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['authentication_directory_id'], ['authentication_directory.id'],
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_group_auth_mapping', 'group_authentication_directory_mappings', ['authentication_directory_id', 'group_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_group_auth_mapping', table_name='group_authentication_directory_mappings')
    op.drop_table('group_authentication_directory_mappings')
    op.drop_index(op.f('ix_mapping_mapping_type'), table_name='mapping')
    op.drop_table('mapping')
    # ### end Alembic commands ###
