"""event_entity

Revision ID: e9bd2522cefd
Revises: f98afc49eec9
Create Date: 2020-01-09 19:03:01.589766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9bd2522cefd'
down_revision = 'f98afc49eec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('entity_uuid', postgresql.UUID(), nullable=True),
    sa.Column('entity_type', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_entity_type'), 'entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_entity_uuid'), 'entity', ['entity_uuid'], unique=False)
    op.create_table('event_entities',
    sa.Column('event_id', postgresql.UUID(), nullable=False),
    sa.Column('entity_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], )
    )
    op.create_index(op.f('ix_controller_status'), 'controller', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controller_status'), table_name='controller')
    op.drop_table('event_entities')
    op.drop_index(op.f('ix_entity_entity_uuid'), table_name='entity')
    op.drop_index(op.f('ix_entity_entity_type'), table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
