"""add description field to events

Revision ID: f72ec69e9658
Revises: fc9c046e7033
Create Date: 2019-12-12 13:52:44.239054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72ec69e9658'
down_revision = 'fc9c046e7033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'description')
    # ### end Alembic commands ###
