#!/bin/bash
# Скрипт имитирует вывод systemctl. Используется для тестирования получения статусов сервисов.

echo "apache2.service loaded active running
postgresql.service loaded active running
redis-server.service loaded active running
vdi-monitor_worker.service loaded active running
vdi-pool_worker.service loaded active running
vdi-web.service loaded active running
ubuntu-fan.service loaded active exited Ubuntu FAN network setup"
