---

- include: install.yml
- include: setup.yml

- stat: path="{{ repmgr_init_log }}"
  register: repmgr_log_stat

- include: master.yml
  when: 
    - repmgr_master == True
    - repmgr_log_stat.stat.exists == False

- include: standby.yml
  when:
    - repmgr_master == False
    - repmgr_log_stat.stat.exists == False
