---

- name: Repmgr | Configure repmgr role
  postgresql_user:
    user: repmgr
    password: "{{ repmgr_db_user_pass }}"
    role_attr_flags: SUPERUSER
  become: true
  become_user: postgres

- name: Repmgr | alter repmgr db user
  postgresql_query:
    query: 'alter user repmgr set search_path TO repmgr, "$user", public'
  become: true
  become_user: postgres

- name: Repmgr | create repmgr db
  postgresql_db:
    name: repmgr
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    owner: repmgr
  become: true
  become_user: postgres

- name: Repmgr | register master
  command: repmgr -f {{ repmgr_config }} primary register --force
  register: repmgr_log
  become: true
  become_user: postgres
  notify:
    - save repmgr log
